### PR TITLE
fix: transformers v5 compatibility

### PR DESCRIPTION
**Pull request by beautifulrem**
sd-scripts v0.10.5 and v0.10.4 have introduced many Anima-related feature improvements and bug fixes, including key support for LoHA, LoKr, and Anima ControlNet-LLLite. However, this repository has not yet been updated accordingly.

## Summary

Ports two upstream fixes from kohya-ss/sd-scripts v0.10.5 so the trainer works on `transformers>=5.0.0` while remaining compatible with 4.x.

Without these changes Anima-Standalone-Trainer fails on transformers v5:
- `ImportError: cannot import name 'CLIPFeatureExtractor' from 'transformers'` — `CLIPFeatureExtractor` was renamed to `CLIPImageProcessor` in 4.x and fully removed in 5.x.
- `AttributeError: 'Qwen2TokenizerFast' object has no attribute 'batch_encode_plus'` — the legacy method is removed in 5.x; the tokenizer should be called directly.
- The slow `Qwen2Tokenizer` / `T5Tokenizer` classes are deprecated; type references should use `Qwen2TokenizerFast` and `PreTrainedTokenizer`.

## Upstream commits ported

- kohya-ss/sd-scripts@fd95682 — update tokenizer references to use `PreTrainedTokenizer` and `Qwen2TokenizerFast`
- kohya-ss/sd-scripts@0be3095 — replace deprecated `CLIPFeatureExtractor` with `CLIPImageProcessor`

Both shipped in sd-scripts v0.10.5 (2026-05-08).

## Changes

| File | Change |
|---|---|
| `library/strategy_anima.py` | `qwen3_tokenizer.batch_encode_plus(...)` and `t5_tokenizer.batch_encode_plus(...)` → direct `__call__` |
| `library/strategy_hunyuan_image.py` | `Qwen2Tokenizer` → `Qwen2TokenizerFast` |
| `library/hunyuan_image_text_encoder.py` | `Qwen2Tokenizer` → `Qwen2TokenizerFast` (5×), `T5Tokenizer` → `PreTrainedTokenizer` (3 type hints + import). The JSON config string `"ByT5Tokenizer"` is intentionally left untouched. |
| `library/lpw_stable_diffusion.py` | `from transformers import CLIPImageProcessor as CLIPFeatureExtractor, ...` |
| `library/sdxl_lpw_stable_diffusion.py` | same as above |

## Compatibility

`requirements.txt` pin of `transformers==4.54.1` is unchanged — code works on both 4.x and 5.x. Users on 5.x should also bump `diffusers` to the latest version (matches upstream README guidance for sd-scripts v0.10.5).

### CODE REVIEW

**Comment by gazingstars123** [comment]
Thanks, import works with transformers 4.
